### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by noahkw** [patjw/theredprison#1]
Hi,

I'm trying to run the game from source but I can't figure out what packages it needs. Specifically the terminal, dbhash, and anydbm imports error out at the moment.
Could you provide a requirements.txt which is generated using `pip freeze > requirements.txt`?
Thanks

**Comment by patjw** [comment]
Hi, sorry for the delay in responding to this. I can't actually easily help with providing a requirements.txt because I'm in the middle of transitioning the project from python 2.7 to 3.

I'm almost certain that the issues that you're having are because I expect you're using python 3, and I've had to remove dbhash and anydbm from the new version to make it work. 

the terminal import is the bearlibterminal library and in the new version it has become:

`from bearlibterminal import terminal as blt`

There's a host of other changes that you would need to make to get it running though, so it's probably not worth going through that same process. I hope to get the python 3 version up in the very near future - I hadn't done so just because it was an experiment as to whether I could even get the game to work with the updated libraries but it all seems good.

**Comment by noahkw** [comment]
No worries!
Yeah, I was trying to run it in a python 3 env.
There's no rush on my end, so I'll happily wait for your py3 port.

Thanks again

**Comment by patjw** [comment]
It should be all good to go now! You'll still need the bearlibterminal.dll but I've got it working for python 3.
